### ISSUE TITLE
Remotes

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-flow-editor#3]
# Goal

Manage remotes of a runtime

### VFS Representation

* File System Provider
  * Runtime
    * System
      * Remotes
        * Remote

### Tasks

- [ ] Fetch the list of remotes from a GraphQL endpoint
- [ ] Extend the VFS with the list of remotes
- [ ] Implement a context menu actions for a remote
  - [ ] Remove a remote
  - [ ] Update a remote
  - [ ] Add the remote as managed runtime
- [ ] Implement a context menu actions for the list of remotes
  - [ ] Add a remote
  - [ ] Update all remotes

### References

* https://github.com/inexorgame/inexor-rgf-application/issues/86
