### ISSUE TITLE
List and edit components of a runtime

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-flow-editor#4]
# Goal

Manage components of a runtime

### Tasks

- [ ] File System Provider
  - [ ] Runtimes
    - [ ] Types
      - [ ] Components
        - [ ] Component → Opens a Component Editor / JSON Editor
          - [ ] Context Menu: Remove Component
        - [ ] Context Menu: Add Component
