### ISSUE TITLE
GraphQL / Dynamic Graph Integration

### ISSUE THREAD

**Issue by aschaeffer** [inexorgame/inexor-rgf-flow-editor#6]
### Goal

VS Code provides a GraphQL extension. A tighter integration would be beneficial.

### Tasks

- [ ] Explore if it's possible to pre-configure the endpoints for the GraphQL and the Dynamic Graph APIs for each runtime
- [ ] Explore if it's possible to provide pre-configured GraphQL queries via the VFS
- [ ] Explore if there is an extension available for GraphQL Playground or if it's possible to create one
